---

- name: Build and upload Docker image
  hosts: localhost
  gather_facts: false

  tasks:
  - name: ecr-repo
    aws.ecs_ecr:
      name: {{ repository_name }}
    register: repository

  - name: Build Docker image
    command: docker build -t task-app:latest .
    args:
      chdir: ../../Dockerfile

  - name: Login to ECR
    aws_ecr_login:
      region: eu-west-1

  - name: Tag Docker image
    command: docker tag task-app:latest {{ repository }}:latest

  - name: Push Docker image to ECR
    command: docker push {{ repository }}:latest


# iam role - lambda execution and also network creation
#  create security group for lambda
# vpc
# route table - private should go to nat
# route table - public should go to igw
# subnets
# db subnet
# lambda subnet
# nat gateway
# allow only api gateway to connect to lambda
# rds security group only allow lambda