---
- hosts: localhost
  connection: local
  gather_facts: false

  vars:
    ecr_image_src_dir: ../../
    ecr_image_name: "{{ repository_name }}"
    ecr_image_tags: "{{ tag }}"
    ecr_account_id: "{{ aws_account_id }}"
    pip_install_packages: ['docker']
    ecr_region: "{{ app_region }}"
    ecr_login_required: false


  roles:
    - role: common
    - role: create_ecr_repo
    # - role: geerlingguy.docker
    # - role: geerlingguy.pip
    # - role: geerlingguy.ecr_container_build
